/*
  Seed sample providers and services for the existing Emergency Service Platform.

  This script only uses the current Mongoose models:
    - backend/Models/Provider.js
    - backend/Models/Services.js

  It does not change schemas, routes, controllers, auth, or project structure.

  Run from the backend folder:
    node seed/seedServicesAndProviders.js
*/

const path = require('path');
const mongoose = require('mongoose');
const dotenv = require('dotenv');

dotenv.config({ path: path.join(__dirname, '..', 'config', 'config.env') });

const Provider = require('../Models/Provider');
const Services = require('../Models/Services');

const providerData = [
  {
    name: 'Bir Hospital',
    providerType: 'hospital',
    description: 'Government hospital in Kathmandu offering emergency care, consultations, and ambulance coordination.',
    location: 'Mahaboudha, Kathmandu',
    phone: '+977-01-4221119',
    email: 'info@birhospital.example.com',
    website: 'https://birhospital.example.com',
    image: '/images/doctor.jpg',
    rating: 4.7,
    reviews: 184,
    verified: true,
    emergencyAvailable: true,
    initials: 'BH',
    active: true,
  },
  {
    name: 'Western Hospital',
    providerType: 'hospital',
    description: 'Regional hospital with emergency treatment, outpatient doctors, and ambulance dispatch support.',
    location: 'New Road, Pokhara',
    phone: '+977-061-540221',
    email: 'contact@westernhospital.example.com',
    website: 'https://westernhospital.example.com',
    image: '/images/doctor.jpg',
    rating: 4.3,
    reviews: 96,
    verified: true,
    emergencyAvailable: true,
    initials: 'WH',
    active: false,
  },
  {
    name: 'Sanjeevani Hospital',
    providerType: 'hospital',
    description: 'Private hospital providing doctor consultations, urgent care, and referral ambulance service.',
    location: 'Milan Chowk, Butwal',
    phone: '+977-071-533099',
    email: 'hello@sanjeevanihospital.example.com',
    website: 'https://sanjeevanihospital.example.com',
    image: '/images/doctor.jpg',
    rating: 4.5,
    reviews: 127,
    verified: true,
    emergencyAvailable: false,
    initials: 'SH',
    active: true,
  },
  {
    name: 'Kathmandu Electric Service',
    providerType: 'electrician',
    description: 'Certified electricians for home wiring, short circuits, sockets, fuses, and power restoration.',
    location: 'Baneshwor, Kathmandu',
    phone: '+977-01-5912345',
    email: 'support@kathelectric.example.com',
    website: 'https://kathelectric.example.com',
    image: '/images/electrician.jpg',
    rating: 4.8,
    reviews: 166,
    verified: true,
    emergencyAvailable: true,
    initials: 'KES',
    active: true,
  },
  {
    name: 'City Electricians',
    providerType: 'electrician',
    description: 'Local electricians handling repairs, switch boards, fuse issues, and household power failures.',
    location: 'Chipledhunga, Pokhara',
    phone: '+977-061-445701',
    email: 'team@cityelectricians.example.com',
    website: 'https://cityelectricians.example.com',
    image: '/images/electrician.jpg',
    rating: 4.1,
    reviews: 58,
    verified: false,
    emergencyAvailable: false,
    initials: 'CE',
    active: false,
  },
  {
    name: 'Nepal Plumbing Service',
    providerType: 'plumber',
    description: 'Professional plumbing team for pipe leaks, drain cleaning, tanks, bathrooms, and supply lines.',
    location: 'Jawalakhel, Lalitpur',
    phone: '+977-01-5523401',
    email: 'help@nepalplumbing.example.com',
    website: 'https://nepalplumbing.example.com',
    image: '/images/plumber.jpg',
    rating: 4.6,
    reviews: 139,
    verified: true,
    emergencyAvailable: false,
    initials: 'NPS',
    active: true,
  },
  {
    name: 'Quick Plumbers',
    providerType: 'plumber',
    description: 'Same-day plumbing repair service for leaks, clogged drains, bathroom fittings, and water supply issues.',
    location: 'Traffic Chowk, Biratnagar',
    phone: '+977-021-520910',
    email: 'office@quickplumbers.example.com',
    website: 'https://quickplumbers.example.com',
    image: '/images/plumber.jpg',
    rating: 4.0,
    reviews: 52,
    verified: false,
    emergencyAvailable: false,
    initials: 'QP',
    active: true,
  },
  {
    name: 'Home Care Services',
    providerType: 'other',
    description: 'Multi-service home maintenance provider for both electrical and plumbing repairs.',
    location: 'Bharatpur, Chitwan',
    phone: '+977-056-590122',
    email: 'care@homecare.example.com',
    website: 'https://homecare.example.com',
    image: '/images/electrician.jpg',
    rating: 4.6,
    reviews: 101,
    verified: true,
    emergencyAvailable: true,
    initials: 'HCS',
    active: true,
  },
];

const serviceData = [
  {
    providerName: 'Bir Hospital',
    category: 'doctor',
    name: 'Doctor Consultation',
    description: 'General and urgent doctor consultation for walk-in and emergency patients.',
    price: 700,
    experience: '15+ years',
    duration: 30,
    available: true,
    capacity: 8,
    rating: 4.8,
    reviews: 74,
    icon: 'hospital',
  },
  {
    providerName: 'Bir Hospital',
    category: 'doctor',
    name: 'Emergency Care',
    description: 'Rapid emergency assessment, triage, and first-line treatment by hospital staff.',
    price: 2500,
    experience: '20+ years',
    duration: 60,
    available: true,
    capacity: 5,
    rating: 4.7,
    reviews: 89,
    icon: 'first-aid',
  },
  {
    providerName: 'Bir Hospital',
    category: 'ambulance',
    name: 'Ambulance Service',
    description: 'Emergency ambulance pickup with trained responder support inside Kathmandu Valley.',
    price: 1800,
    experience: '24/7 emergency team',
    duration: 45,
    available: true,
    capacity: 3,
    rating: 4.6,
    reviews: 62,
    icon: 'ambulance',
  },
  {
    providerName: 'Western Hospital',
    category: 'doctor',
    name: 'Doctor Consultation',
    description: 'Consultation with duty doctors for fever, injuries, and urgent medical advice.',
    price: 650,
    experience: '12+ years',
    duration: 30,
    available: false,
    capacity: 4,
    rating: 4.2,
    reviews: 44,
    icon: 'hospital',
  },
  {
    providerName: 'Western Hospital',
    category: 'doctor',
    name: 'Emergency Care',
    description: 'Emergency stabilization and referral support for serious medical conditions.',
    price: 2200,
    experience: '18+ years',
    duration: 60,
    available: false,
    capacity: 3,
    rating: 4.3,
    reviews: 51,
    icon: 'first-aid',
  },
  {
    providerName: 'Western Hospital',
    category: 'ambulance',
    name: 'Ambulance Service',
    description: 'Ambulance dispatch for urgent hospital transport in Pokhara and nearby areas.',
    price: 2000,
    experience: '10+ years',
    duration: 50,
    available: false,
    capacity: 2,
    rating: 4.1,
    reviews: 37,
    icon: 'ambulance',
  },
  {
    providerName: 'Sanjeevani Hospital',
    category: 'doctor',
    name: 'Doctor Consultation',
    description: 'Outpatient consultation for common illness, injuries, and follow-up care.',
    price: 600,
    experience: '11+ years',
    duration: 25,
    available: true,
    capacity: 6,
    rating: 4.5,
    reviews: 57,
    icon: 'hospital',
  },
  {
    providerName: 'Sanjeevani Hospital',
    category: 'doctor',
    name: 'Emergency Care',
    description: 'Urgent care for injuries, fever, dehydration, and emergency observation.',
    price: 2100,
    experience: '16+ years',
    duration: 55,
    available: true,
    capacity: 4,
    rating: 4.4,
    reviews: 63,
    icon: 'first-aid',
  },
  {
    providerName: 'Sanjeevani Hospital',
    category: 'ambulance',
    name: 'Ambulance Service',
    description: 'Referral ambulance service for hospital transfers and emergency pickups.',
    price: 1700,
    experience: 'On-call ambulance team',
    duration: 45,
    available: false,
    capacity: 1,
    rating: 4.2,
    reviews: 31,
    icon: 'ambulance',
  },
  {
    providerName: 'Kathmandu Electric Service',
    category: 'electrician',
    name: 'Short Circuit Repair',
    description: 'Inspection and repair of short circuit faults with safety checks.',
    price: 1200,
    experience: '9+ years',
    duration: 60,
    available: true,
    capacity: 3,
    rating: 4.8,
    reviews: 82,
    icon: 'bolt',
  },
  {
    providerName: 'Kathmandu Electric Service',
    category: 'electrician',
    name: 'House Wiring',
    description: 'Complete or partial house wiring for rooms, flats, and small offices.',
    price: 8500,
    experience: '10+ years',
    duration: 240,
    available: true,
    capacity: 1,
    rating: 4.7,
    reviews: 69,
    icon: 'wiring',
  },
  {
    providerName: 'Kathmandu Electric Service',
    category: 'electrician',
    name: 'Fuse Replacement',
    description: 'Fuse replacement with load testing and basic circuit inspection.',
    price: 650,
    experience: '8+ years',
    duration: 30,
    available: true,
    capacity: 5,
    rating: 4.6,
    reviews: 54,
    icon: 'fuse',
  },
  {
    providerName: 'Kathmandu Electric Service',
    category: 'electrician',
    name: 'Switch & Socket Repair',
    description: 'Repair and replacement of switches, sockets, holders, and loose connections.',
    price: 900,
    experience: '8+ years',
    duration: 40,
    available: true,
    capacity: 4,
    rating: 4.7,
    reviews: 73,
    icon: 'socket',
  },
  {
    providerName: 'Kathmandu Electric Service',
    category: 'electrician',
    name: 'Power Failure Repair',
    description: 'Troubleshooting sudden power loss in homes and small businesses.',
    price: 1500,
    experience: '9+ years',
    duration: 75,
    available: false,
    capacity: 2,
    rating: 4.5,
    reviews: 46,
    icon: 'power',
  },
  {
    providerName: 'City Electricians',
    category: 'electrician',
    name: 'Fuse Replacement',
    description: 'Quick fuse replacement and distribution board inspection.',
    price: 600,
    experience: '5+ years',
    duration: 30,
    available: false,
    capacity: 2,
    rating: 4.0,
    reviews: 22,
    icon: 'fuse',
  },
  {
    providerName: 'City Electricians',
    category: 'electrician',
    name: 'Switch & Socket Repair',
    description: 'Repair damaged switches, sockets, and basic wiring faults.',
    price: 800,
    experience: '6+ years',
    duration: 45,
    available: false,
    capacity: 2,
    rating: 4.1,
    reviews: 27,
    icon: 'socket',
  },
  {
    providerName: 'Nepal Plumbing Service',
    category: 'plumber',
    name: 'Pipe Leakage Repair',
    description: 'Leak detection and pipe repair for kitchens, bathrooms, and supply lines.',
    price: 1300,
    experience: '8+ years',
    duration: 75,
    available: true,
    capacity: 3,
    rating: 4.7,
    reviews: 76,
    icon: 'pipe',
  },
  {
    providerName: 'Nepal Plumbing Service',
    category: 'plumber',
    name: 'Drain Cleaning',
    description: 'Cleaning and unclogging slow or blocked drains using safe tools.',
    price: 1100,
    experience: '7+ years',
    duration: 60,
    available: true,
    capacity: 3,
    rating: 4.5,
    reviews: 61,
    icon: 'drain',
  },
  {
    providerName: 'Nepal Plumbing Service',
    category: 'plumber',
    name: 'Water Tank Repair',
    description: 'Repair tank leakage, inlet issues, outlet fittings, and overflow problems.',
    price: 3000,
    experience: '9+ years',
    duration: 150,
    available: false,
    capacity: 1,
    rating: 4.4,
    reviews: 43,
    icon: 'water-tank',
  },
  {
    providerName: 'Nepal Plumbing Service',
    category: 'plumber',
    name: 'Bathroom Plumbing',
    description: 'Repair bathroom taps, flush systems, shower lines, and floor drainage.',
    price: 1600,
    experience: '8+ years',
    duration: 90,
    available: true,
    capacity: 2,
    rating: 4.6,
    reviews: 58,
    icon: 'bathroom',
  },
  {
    providerName: 'Nepal Plumbing Service',
    category: 'plumber',
    name: 'Water Supply Repair',
    description: 'Fix low water pressure, blocked supply lines, and interrupted water flow.',
    price: 1800,
    experience: '8+ years',
    duration: 90,
    available: true,
    capacity: 2,
    rating: 4.5,
    reviews: 49,
    icon: 'water',
  },
  {
    providerName: 'Quick Plumbers',
    category: 'plumber',
    name: 'Pipe Leakage Repair',
    description: 'Same-day repair for small to medium pipe leaks.',
    price: 1200,
    experience: '5+ years',
    duration: 70,
    available: true,
    capacity: 2,
    rating: 4.1,
    reviews: 29,
    icon: 'pipe',
  },
  {
    providerName: 'Quick Plumbers',
    category: 'plumber',
    name: 'Drain Cleaning',
    description: 'Fast drain cleaning for kitchens, bathrooms, and utility areas.',
    price: 950,
    experience: '5+ years',
    duration: 55,
    available: false,
    capacity: 2,
    rating: 4.0,
    reviews: 24,
    icon: 'drain',
  },
  {
    providerName: 'Home Care Services',
    category: 'electrician',
    name: 'House Wiring',
    description: 'Home wiring repair and small electrical installation work.',
    price: 7800,
    experience: '7+ years',
    duration: 210,
    available: true,
    capacity: 1,
    rating: 4.6,
    reviews: 45,
    icon: 'wiring',
  },
  {
    providerName: 'Home Care Services',
    category: 'electrician',
    name: 'Switch & Socket Repair',
    description: 'Repair or replace worn switches, sockets, and loose connections.',
    price: 850,
    experience: '7+ years',
    duration: 45,
    available: true,
    capacity: 2,
    rating: 4.5,
    reviews: 39,
    icon: 'socket',
  },
  {
    providerName: 'Home Care Services',
    category: 'electrician',
    name: 'Power Failure Repair',
    description: 'Diagnosis and repair for household power interruptions.',
    price: 1400,
    experience: '7+ years',
    duration: 75,
    available: true,
    capacity: 2,
    rating: 4.4,
    reviews: 34,
    icon: 'power',
  },
  {
    providerName: 'Home Care Services',
    category: 'plumber',
    name: 'Pipe Leakage Repair',
    description: 'Pipe leakage repair with sealing, fitting replacement, and pressure testing.',
    price: 1250,
    experience: '7+ years',
    duration: 80,
    available: true,
    capacity: 2,
    rating: 4.6,
    reviews: 42,
    icon: 'pipe',
  },
  {
    providerName: 'Home Care Services',
    category: 'plumber',
    name: 'Water Supply Repair',
    description: 'Repair interrupted or low-pressure water supply lines.',
    price: 1750,
    experience: '7+ years',
    duration: 95,
    available: false,
    capacity: 1,
    rating: 4.4,
    reviews: 31,
    icon: 'water',
  },
  {
    providerName: 'Home Care Services',
    category: 'plumber',
    name: 'Bathroom Plumbing',
    description: 'Bathroom fixture repair, tap replacement, and drainage fixes.',
    price: 1500,
    experience: '7+ years',
    duration: 85,
    available: true,
    capacity: 2,
    rating: 4.5,
    reviews: 36,
    icon: 'bathroom',
  },
];

async function seedProviders() {
  const providerMap = new Map();

  for (const provider of providerData) {
    const savedProvider = await Provider.findOneAndUpdate(
      { name: provider.name },
      provider,
      { new: true, upsert: true, runValidators: true, setDefaultsOnInsert: true }
    );

    providerMap.set(savedProvider.name, savedProvider);
  }

  return providerMap;
}

async function seedServices(providerMap) {
  let seededCount = 0;

  for (const service of serviceData) {
    const provider = providerMap.get(service.providerName);

    if (!provider) {
      throw new Error(`Provider not found for service "${service.name}": ${service.providerName}`);
    }

    const { providerName, ...serviceFields } = service;

    await Services.findOneAndUpdate(
      {
        provider: provider._id,
        category: service.category,
        name: service.name,
      },
      {
        ...serviceFields,
        provider: provider._id,
      },
      { new: true, upsert: true, runValidators: true, setDefaultsOnInsert: true }
    );

    seededCount += 1;
  }

  return seededCount;
}

async function main() {
  if (!process.env.MONGO_URI) {
    throw new Error('MONGO_URI is missing from backend/config/config.env');
  }

  await mongoose.connect(process.env.MONGO_URI, { family: 4 });

  const providerMap = await seedProviders();
  const serviceCount = await seedServices(providerMap);

  console.log(`Seed complete: ${providerMap.size} providers and ${serviceCount} services are ready.`);
}

main()
  .catch((error) => {
    console.error('Seeding failed:', error.message);
    process.exitCode = 1;
  })
  .finally(async () => {
    await mongoose.disconnect();
  });
